### ISSUE TITLE
Cover_index, cover_detail image paths

### ISSUE THREAD

**Issue by patrickbolle** [klugjo/hexo-theme-phantom#6]
Hey there, loving this theme so far.
Trying to add the images to each post currently

I have Hexo on the "post_asset_folder: true" setting, meaning I've got the asset folder within each post folder. Example - _posts - > test.md & test (folder where I put my images.

I'm trying to access my images just using the "cover_index: test.png" but it's saying no such image exists.

Do you know how I would figure this out?

Thanks !

Edit - 
Alright so I got the images working sort of - 

My current paths are: 
cover_index: ./2016/04/25/test/test.png  ( I don't really like having to do this, but it makes sense that it's needed ) 
cover_detail: test.png

This works perfect for the most part - 
But on my /tags/ pages, I modified your code to include the images as well, not just the post title - 

In here, my images dont show up unless I do a wacky "../../2016/04/25/test/test.png" etc

I'll look into the code a bit more and see if I can hack something together for this.

Thanks again!

**Comment by klugjo** [comment]
Hi Patrick,

I get your point, this is not really the way Hexo wants you to do it actually. Maybe there is a way to modify the theme to make it work the way you want.

I would highly recommend you store all your images in a dedicated image folder.

i.e

`[root of blog]/source/image/test/test.png`

and in your post simply access it by 

`/image/test/test.png`

In other words, you create the same folder structure as in `_posts` but in an `image` folder.

This is kind of the way Hexo wants you to do it, and I also believe it is much cleaner. Otherwise if you ever need to change the date of your posts, you will have to change the image path as well which sounds crazy.

Let me know if that works for you
